version: '2.2'

services:
  apt-cacher-ng:
    restart: always
    image: chenz/apt-cacher-ng
    network_mode: "host"
    init: true
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
