version: '3.1'

services:
  nexus3:
    image: sonatype/nexus3
    volumes:
        - nexus-data:/nexus-data
    network_mode: host
    restart: always
    init: true

volumes:
    nexus-data:
        external: false
